### ISSUE TITLE
Missing return value in function `ident_add_char`

### ISSUE THREAD

**Issue by mingodad** [FransFaase/RawParser#1]
Testing this project with different compilers I found that they do not output the same thing and digging the issue I found the it here https://github.com/tyfkda/xcc/issues/96#issuecomment-1236076743

**Comment by mingodad** [comment]
And there is several other functions that doesn't return anything but should.

**Comment by FransFaase** [comment]
I close this issue, because it seems this has been fixed about two years ago in the commit 91c5425014023ed44ea2ffdf2d7ac519c42f47dc. In the latest commit the function `ident_add_char` ends with a `return TRUE;` statement.

I could not find any other function without a return statement at the end except for the function `ident_string` where the return is in the preceding for statement. The for statement has not termination condition.

**Comment by mingodad** [comment]
Thank you for pointing out my mistake !
I mean I had an old clone on my computer and used it without first do a `pull` to check if anything has changed since my last clone/pull.
